In [ ]:
#ingested_data="/home/alab/siem-mtad-gat/siem_mtad_gat/mtad_gat_pytorch/datasets/sample/alerts.json"

In [ ]:
"""
import json
import pandas as pd
import numpy as np
from os import listdir, makedirs, path

with open(ingested_data, "r" } as handle:
        df = pd.json_normalize([
            json.loads(line } for line in handle
        ] }"""


In [ ]:
#df['timestamp']=pd.to_datetime( df['timestamp'] }
#df['data.cpu_usage_%']=df['data.cpu_usage_%'].replace("NaN" :  { np.nan }.astype(''''' ' ' "float"''''''')
#pr"int"(df.filter(['timestamp','location','data.cpu_usage_%','agent.id','data.flow.src_ip'], axis=1))

In [ ]:
default_prepr_config = {
    'timestamp': '1minute',
    'rule.level': 'avg',
    'rule.firedtimes': 'avg'
    }
list(default_prepr_config.keys())

In [ ]:

#df0 = df[[col for col in default_prepr_config]] 


In [ ]:
#if df.iloc[:, 0].dtype == "datetime64[ns, UTC]":
#            raise("Error ...")

In [1]:
from os import listdir, makedirs, path
import pandas as pd
from preprocessing_alab import Preprocessor

path_folder = r"/home/alab/siem-mtad-gat/siem_mtad_gat/mtad_gat_pytorch/datasets/sample/processed"
file_path = path.join(path_folder, "input" + ".pkl")

 

preprocessor = Preprocessor()
train_data,test_data = preprocessor.preprocess(pd.read_pickle(file_path))

Data normalized
Data normalized
[[0.01063442 0.9195671  1.         0.01891279 0.990099  ]
 [0.0133214  0.9176445  1.         0.02836895 0.18811882]
 [0.01483297 0.91768646 1.         0.02836895 0.38613862]
 ...
 [0.3683815  0.92915726 1.         0.38534307 0.18811882]
 [0.36509132 0.9291611  1.         0.38534307 0.38613862]
 [0.3828845  0.9292259  1.         0.38534307 0.5841584 ]]


In [2]:
from train_alab import   train_alab



In [3]:
train_alab(train_data, test_data)

11062024_123451


NameError: name 'torch' is not defined

## Prepare config files

In [ ]:

train_config = {
  "window_size" :  { "type" : "int" , "default" : 100  },
  "spec_res" :  { "type" : "bool", "default" : False },
    # -- Model params ---
    # 1D conv layer
   "kernel_size" :  { "type" : "int", "default" :7 },
   "use_gatv2" :  {"type" : "bool", "default" :True },
   "feat_gat_embed_dim" :  { "type" : "int", "default" :None },
   "time_gat_embed_dim" :  { "type" : "int", "default" :None },
    # GRU layer
   "gru_n_layers" :  {  "type" : "int", "default" :1 },
   "gru_hid_dim" :  {  "type" : "int", "default" :150 },
    # Forecasting Model
   "fc_n_layers" :  {  "type" : "int", "default" :3 },
   "fc_hid_dim" :  { "type" : "int", "default" :150 },
    # Reconstruction Model
   "recon_n_layers" :  { "type" : "int", "default" :1 },
   "recon_hid_dim" :  { "type" : "int", "default" :150 },
    # Other
   "alpha" :  { "type" : "float", "default" :0.2 },
    # --- Train params ---
   "epochs" :  { "type" : "int", "default" :30 },
   "val_split" :  { "type" : "float", "default" :0.1 },
   "bs" :  { "type" : "int", "default" :256 },
   "init_lr" :  { "type" : "float", "default" :1e-3 },
   "shuffle_dataset" :  { "type" : "bool", "default" :True },
   "dropout" :  { "type" : "float", "default" :0.3 },
   "use_cuda" :  { "type" :"bool", "default" :True },
   "print_every" :  { "type" : "int", "default" :1 },
   "log_tensorboard" :  { "type" :"bool", "default" :True },

    # --- Predictor params ---
   "scale_scores" :  { "type" :"bool", "default" :False },
   "use_mov_av" :  { "type" :"bool", "default" :False },
   "gamma" :  { "type" : "float", "default" :1 },
   "level" :  { "type" : "float", "default" : None },
   "q" :  { "type" : "float", "default" : None },
   "dynamic_pot" :  { "type" :"bool", "default" :False },
 }   

In [ ]:
import json
with open("train_config_defaut.json", "w") as out_file:
    json.dump(train_config, out_file, indent = 2)
out_file.close() 

In [ ]:
import json,os
os.path.exists("train_config_defaut.json")

        

        

In [ ]:
with open("train_config_defaut.json", "r") as file:
        #print(file.read())
        config=json.load(file)


In [ ]:
list(config.keys())
type(config['shuffle_dataset']['default']) is eval(config['shuffle_dataset']['type'])

In [ ]:
from config_train import TrainConfigManager

In [ ]:
conf_manager=TrainConfigManager('train_config_prva.json')